node {
  name = "emqx@0.0.0.0"
  cookie = "emqxsecretcookie"
  data_dir = "data"
}

cluster {
  name = emqx
  discovery_strategy = manual
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024000
}

dashboard.listeners.http.bind = "0.0.0.0:18083"
